=== Nxssie/HIV-XSL/public/XML_XSL/hivdata.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.artiigo.com"
           xmlns = "https://www.artiigo.com"
           elementFormDefault="qualified">
    <xs:element name="hiv">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="data" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="country" type="xs:string"/>
                            <xs:element name="year" type="xs:string"/>
                            <xs:element name="display" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Nxssie/HIV-XSL/hivdata_output.xml
<?xml version="1.0" encoding="UTF-8"?>
<hiv xmlns:x="https://www.artiigo.com"
     xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation = "https://www.artiigo.com hivdata.xsd">
    <data>
        <country>Afghanistan</country>
        <year>2000</year>
        <display>1600 [1000–3500]</display>
    </data>
    <data>
        <country>Albania</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Algeria</country>
        <year>2000</year>
        <display>1900 [1700–2000]</display>
    </data>
    <data>
        <country>Angola</country>
        <year>2000</year>
        <display>87 000 [72 000–110 000]</display>
    </data>
    <data>
        <country>Argentina</country>
        <year>2000</year>
        <display>64 000 [55 000–71 000]</display>
    </data>
    <data>
        <country>Armenia</country>
        <year>2000</year>
        <display>950 [580–1600]</display>
    </data>
    <data>
        <country>Australia</country>
        <year>2000</year>
        <display>13 000 [11 000–15 000]</display>
    </data>
    <data>
        <country>Austria</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Azerbaijan</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Bahamas</country>
        <year>2000</year>
        <display>5100 [4400–5900]</display>
    </data>
    <data>
        <country>Bahrain</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Bangladesh</country>
        <year>2000</year>
        <display>940 [800–1100]</display>
    </data>
    <data>
        <country>Barbados</country>
        <year>2000</year>
        <display>1100 [1000–1300]</display>
    </data>
    <data>
        <country>Belarus</country>
        <year>2000</year>
        <display>1400 [1100–1900]</display>
    </data>
    <data>
        <country>Belgium</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Belize</country>
        <year>2000</year>
        <display>1700 [1600–1800]</display>
    </data>
    <data>
        <country>Benin</country>
        <year>2000</year>
        <display>47 000 [31 000–75 000]</display>
    </data>
    <data>
        <country>Bhutan</country>
        <year>2000</year>
        <display>530 [&lt;200–970]</display>
    </data>
    <data>
        <country>Bolivia (Plurinational State of)</country>
        <year>2000</year>
        <display>21 000 [20 000–23 000]</display>
    </data>
    <data>
        <country>Bosnia and Herzegovina</country>
        <year>2000</year>
        <display>&lt;100 [&lt;100–&lt;100]</display>
    </data>
    <data>
        <country>Botswana</country>
        <year>2000</year>
        <display>280 000 [270 000–300 000]</display>
    </data>
    <data>
        <country>Brazil</country>
        <year>2000</year>
        <display>410 000 [320 000–510 000]</display>
    </data>
    <data>
        <country>Brunei Darussalam</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Bulgaria</country>
        <year>2000</year>
        <display>&lt;500 [&lt;500–&lt;500]</display>
    </data>
    <data>
        <country>Burkina Faso</country>
        <year>2000</year>
        <display>140 000 [110 000–170 000]</display>
    </data>
    <data>
        <country>Burundi</country>
        <year>2000</year>
        <display>130 000 [110 000–150 000]</display>
    </data>
    <data>
        <country>Cambodia</country>
        <year>2000</year>
        <display>81 000 [73 000–91 000]</display>
    </data>
    <data>
        <country>Cameroon</country>
        <year>2000</year>
        <display>370 000 [350 000–410 000]</display>
    </data>
    <data>
        <country>Canada</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Cabo Verde</country>
        <year>2000</year>
        <display>1600 [1200–2500]</display>
    </data>
    <data>
        <country>Central African Republic</country>
        <year>2000</year>
        <display>160 000 [130 000–190 000]</display>
    </data>
    <data>
        <country>Chad</country>
        <year>2000</year>
        <display>80 000 [60 000–100 000]</display>
    </data>
    <data>
        <country>Chile</country>
        <year>2000</year>
        <display>14 000 [13 000–16 000]</display>
    </data>
    <data>
        <country>China</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Colombia</country>
        <year>2000</year>
        <display>110 000 [91 000–130 000]</display>
    </data>
    <data>
        <country>Comoros</country>
        <year>2000</year>
        <display>&lt;100 [&lt;100–&lt;100]</display>
    </data>
    <data>
        <country>Congo</country>
        <year>2000</year>
        <display>80 000 [64 000–96 000]</display>
    </data>
    <data>
        <country>Costa Rica</country>
        <year>2000</year>
        <display>4300 [3700–4700]</display>
    </data>
    <data>
        <country>Côte d'Ivoire</country>
        <year>2000</year>
        <display>590 000 [470 000–740 000]</display>
    </data>
    <data>
        <country>Croatia</country>
        <year>2000</year>
        <display>&lt;500 [&lt;500–&lt;500]</display>
    </data>
    <data>
        <country>Cuba</country>
        <year>2000</year>
        <display>4100 [2900–5000]</display>
    </data>
    <data>
        <country>Cyprus</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Czechia</country>
        <year>2000</year>
        <display>510 [&lt;500–580]</display>
    </data>
    <data>
        <country>Democratic People's Republic of Korea</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Democratic Republic of the Congo</country>
        <year>2000</year>
        <display>540 000 [470 000–610 000]</display>
    </data>
    <data>
        <country>Denmark</country>
        <year>2000</year>
        <display>4000 [3600–4600]</display>
    </data>
    <data>
        <country>Djibouti</country>
        <year>2000</year>
        <display>9400 [7200–12 000]</display>
    </data>
    <data>
        <country>Dominican Republic</country>
        <year>2000</year>
        <display>85 000 [62 000–120 000]</display>
    </data>
    <data>
        <country>Ecuador</country>
        <year>2000</year>
        <display>26 000 [15 000–46 000]</display>
    </data>
    <data>
        <country>Egypt</country>
        <year>2000</year>
        <display>1500 [1400–1600]</display>
    </data>
    <data>
        <country>El Salvador</country>
        <year>2000</year>
        <display>18 000 [14 000–23 000]</display>
    </data>
    <data>
        <country>Equatorial Guinea</country>
        <year>2000</year>
        <display>13 000 [9200–18 000]</display>
    </data>
    <data>
        <country>Eritrea</country>
        <year>2000</year>
        <display>16 000 [12 000–20 000]</display>
    </data>
    <data>
        <country>Estonia</country>
        <year>2000</year>
        <display>3400 [2900–3900]</display>
    </data>
    <data>
        <country>Eswatini</country>
        <year>2000</year>
        <display>110 000 [98 000–120 000]</display>
    </data>
    <data>
        <country>Ethiopia</country>
        <year>2000</year>
        <display>750 000 [570 000–980 000]</display>
    </data>
    <data>
        <country>Fiji</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Finland</country>
        <year>2000</year>
        <display>1100 [850–1400]</display>
    </data>
    <data>
        <country>France</country>
        <year>2000</year>
        <display>82 000 [69 000–97 000]</display>
    </data>
    <data>
        <country>Gabon</country>
        <year>2000</year>
        <display>28 000 [20 000–38 000]</display>
    </data>
    <data>
        <country>Gambia</country>
        <year>2000</year>
        <display>9900 [7200–13 000]</display>
    </data>
    <data>
        <country>Georgia</country>
        <year>2000</year>
        <display>980 [720–1300]</display>
    </data>
    <data>
        <country>Germany</country>
        <year>2000</year>
        <display>45 000 [37 000–54 000]</display>
    </data>
    <data>
        <country>Ghana</country>
        <year>2000</year>
        <display>270 000 [240 000–300 000]</display>
    </data>
    <data>
        <country>Greece</country>
        <year>2000</year>
        <display>No data</display>
    </data>
    <data>
        <country>Guatemala</country>
        <year>2000</year>
        <display>44 000 [41 000–47 000]</display>
    </data>
    <data>
        <country>Guinea</country>
        <year>2000</year>
        <display>83 000 [67 000–100 000]</display>
    </data>
    <data>
        <country>Guinea-Bissau</country>
        <year>2000</year>
        <display>22 000 [20 000–25 000]</display>
    </data>
    <data>
        <country>Guyana</country>
        <year>2000</year>
        <display>2300 [1600–3100]</display>
    </data>
    <data>
        <country>Haiti</country>
        <year>2000</year>
        <display>150 000 [130 000–180 000]</display>
    </data>
    <data>
        <country>Honduras</country>
        <year>2000</year>
        <display>40 000 [34 000–49 000]</display>
    </data>
    <data>
        <country>Hungary</country>
        <year>2000</year>
        <display>830 [700–950]</display>
    </data>
    <data>
        <country>Iceland</country>
        <year>2000</year>
        <display>&lt;100 [&lt;100–&lt;200]</display>
    </data>
    <data>
        <country>India</country>
        <year>2000</year>
        <display>No data</display>
